language: python
cache: pip
dist: xenial
python:
  - "3.7"
services:
  - docker
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - sleep 10
  - docker run -p 389:389 -p 636:636 --name openldap_server -d osixia/openldap:1.3.0
  - psql -c 'create database buildly_api;' -U postgres
  - sudo touch /var/log/buildly.log
  - sudo chown travis /var/log/buildly.log
install:
  - cat requirements/base.txt | grep "^Django==\|^psycopg2" | xargs pip install
  - pip install -r requirements/ci.txt
  - pip install awscli
script:
  - flake8
  - bandit -r . -ll
  - pytest --cov-config=.coveragerc --cache-clear
  - docker build -t $DOCKER_REPO .
env:
  global:
    ALLOWED_HOSTS: "*"
    CORS_ORIGIN_WHITELIST: "*"
    DATABASE_ENGINE: "postgresql"
    DATABASE_NAME: "buildly_api"
    DATABASE_USER: "postgres"
    DATABASE_PASSWORD: ""
    DATABASE_HOST: "localhost"
    DATABASE_PORT: "5432"
    DEFAULT_ORG: "Default Organization"
    DJANGO_SETTINGS_MODULE: "buildly.settings.production"
    SOCIAL_AUTH_GITHUB_REDIRECT_URL: "/complete/github"
    SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URL: "/complete/google-oauth2"
    SOCIAL_AUTH_MICROSOFT_GRAPH_REDIRECT_URL: "/complete/microsoft-graph"
    JWT_ISSUER: "buildly"
    JWT_PRIVATE_KEY_RSA_BUILDLY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT3dJQkFBSkJBTEZjOU5GWmFPYVN3VU1QTmVrdGJ0SnFFallaNklSQnFocXZKdTFoS1BZbjlIWWQ3NWMwCmdJRFlISjlsYjdRd1F2ZzQ0YU8yNzEwNHJESzB4U3N0ekwwQ0F3RUFBUUpBZTV6NTA5Nm95ZXFHWDZKK1JHR3gKMTF5dURKN0orME40dHRoVUhTV1dVdGdrZDE5TnZtVE0vbVZMbVBDelpIZ05VVCthV1VLc1E4NCtqaHJ1L05RRAowUUloQU9IT3pGbWp4alRBUjFqc3BuNll0SkJLUUI0MHR2VDZXRXZtMm1LbTBhRDdBaUVBeVJQd1h5WmYzSlQrCk02VWkwTXViczdRYi9FNGcxZC9rVkwrby9Yb1pDNmNDSVFDK25LelB0bm9vS1crUTF5T3NsZ2RHRGdlVjkvWEIKVWxxYXArTU5oN2hKWlFJZ1pOYU0rd3FobEZ0Yng4YU8yU3Jpb0pJNFhxVkhyam9qcGFTZ09NM2NkWTBDSVFEQgpRNmNrT2FEVjkzN2FjbVd1aVpoeHVHMmV1Tkx3TmJNbGR0Q1Y1QURvL2c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
    JWT_PUBLIC_KEY_RSA_BUILDLY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTEZjOU5GWmFPYVN3VU1QTmVrdGJ0SnFFallaNklSQgpxaHF2SnUxaEtQWW45SFlkNzVjMGdJRFlISjlsYjdRd1F2ZzQ0YU8yNzEwNHJESzB4U3N0ekwwQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ==
    SECRET_KEY: "nothing"
    OAUTH_CLIENT_ID: "vBn4KsOCthm7TWzMH0kVV0dXkUPJEtOQwaLu0eoC"
    OAUTH_CLIENT_SECRET: "0aYDOHUNAxK4MjbnYOHhfrKx8EzjKqN6GbB6IGyCgpT6pmQ5pEVJmH7mIEUJ"
    DOCKER_REPO: "transparent-path/buildly-core"
    LDAP_ENABLE: "True"
    LDAP_HOST: "ldap://localhost:389"
    LDAP_USERNAME: "cn=admin,dc=example,dc=org"
    LDAP_PASSWORD: "admin"
    LDAP_BASE_DN: "dc=example,dc=org"
deploy:
  provider: script
  script: bash scripts/deploy-aws.sh
  on:
    branch: master
    tags: true
