# Generated by Django 2.2.10 on 2023-06-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='abbrevation',
            field=models.CharField(blank=True, default='DEFAULT', max_length=7, verbose_name='Organization Abbrevation'),
        ),
    ]
