# Generated by Django 2.2.10 on 2023-11-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230913_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_fujitsu_verification',
            field=models.BooleanField(default=False, verbose_name='Enable Fujitsu Integration for verification of shipment data'),
        ),
    ]
