# Generated by Django 2.2.10 on 2024-01-08 09:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_enable_fujitsu_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreuser',
            name='email_preferences',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='push_preferences',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email_notify_environmental',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email_notify_geofence',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='push_notify_environmental',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='push_notify_geofence',
        ),
        migrations.AddField(
            model_name='coreuser',
            name='env_alert_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'email': True, 'sms': False, 'whatsApp': False}, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='geo_alert_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'email': True, 'sms': False, 'whatsApp': False}, null=True),
        ),
    ]
