# Generated by Django 2.2.10 on 2024-01-08 09:30

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240108_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='env_alert_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=core.models.get_preferences_default, null=True),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='geo_alert_preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=core.models.get_preferences_default, null=True),
        ),
    ]
