# Generated by Django 2.2.10 on 2024-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240108_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='sms_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='whatsApp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
