# Generated by Django 2.2.10 on 2024-01-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240108_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_env_emails',
            field=models.BooleanField(default=False, verbose_name='Enable Geofence Alerts'),
        ),
        migrations.AddField(
            model_name='organization',
            name='enable_geofence_emails',
            field=models.BooleanField(default=False, verbose_name='Enable Geofence Alerts'),
        ),
    ]
