# Generated by Django 2.2.10 on 2024-01-26 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coreuser_last_gdpr_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alerts_to_supress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Alert type to supress'), blank=True, default=[], null=True, size=None),
        ),
    ]
