# Generated by Django 2.2.10 on 2024-03-11 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_organization_alerts_to_supress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='alerts_to_supress',
        ),
        migrations.AddField(
            model_name='organization',
            name='alerts_to_suppress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Alert type to suppress'), blank=True, default=[], null=True, size=None),
        ),
    ]
