# Generated by Django 2.2.10 on 2024-03-12 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240311_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='alerts_to_suppress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Alert type to suppress'), blank=True, default=list, null=True, size=None),
        ),
    ]
