# Generated by Django 2.2.10 on 2024-05-20 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240313_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_reseller',
            field=models.BooleanField(default=False, verbose_name='To mark as reseller'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reseller_customer_orgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=63), blank=True, help_text='All customer organizations associated with this reseller.', null=True, size=None),
        ),
    ]
