# Generated by Django 2.2.10 on 2024-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240520_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='user_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
