# Generated by Django 5.0.13 on 2025-03-24 14:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coreuser_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='env_alert_preferences',
            field=models.JSONField(blank=True, default=core.models.get_preferences_default, null=True),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='coreuser',
            name='geo_alert_preferences',
            field=models.JSONField(blank=True, default=core.models.get_preferences_default, null=True),
        ),
        migrations.AlterField(
            model_name='logicmodule',
            name='api_specification',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
