# Generated by Django 2.2.10 on 2025-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coreuser_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='map_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='map_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
