# Generated by Django 2.2.10 on 2025-01-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20250109_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coreuser',
            name='map_language',
        ),
        migrations.RemoveField(
            model_name='coreuser',
            name='map_region',
        ),
    ]
