# Generated by Django 5.0.14 on 2025-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_coreuser_env_alert_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicmodule',
            name='swagger_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
