# Generated by Django 5.0.14 on 2025-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_logicmodule_swagger_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='default_measurement_interval',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='default_transmission_interval',
        ),
        migrations.AddField(
            model_name='organization',
            name='default_post_transit_measurement_interval',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='Interval in minutes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_post_transit_transmission_interval',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='Interval in minutes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_pre_transit_measurement_interval',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='Interval in minutes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_pre_transit_transmission_interval',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='Interval in minutes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_transit_measurement_interval',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Interval in minutes'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_transit_transmission_interval',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Interval in minutes'),
        ),
    ]
