# Generated by Django 5.0.14 on 2025-08-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_organization_default_measurement_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_tilt',
            field=models.BooleanField(default=False, verbose_name='Enable Tilt'),
        ),
    ]
