# Generated by Django 5.0.14 on 2025-09-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_organization_enable_tilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_transit_measurement_interval',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='Interval in minutes'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_transit_transmission_interval',
            field=models.IntegerField(blank=True, default=120, null=True, verbose_name='Interval in minutes'),
        ),
    ]
