# Generated by Django 5.0.14 on 2026-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_organization_default_transit_measurement_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_platform',
            field=models.CharField(blank=True, default='Tive', max_length=255, verbose_name='Default Sensor Platform'),
        ),
    ]
