# Generated by Django 5.0 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='profile_pic',
            field=models.TextField(
                blank=True,
                null=True,
                help_text='Base64-encoded profile picture (data URL)',
            ),
        ),
    ]
