# Generated by Django 5.0 on 2026-08-13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_coreuser_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_jti', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('organization_name_at_issue', models.CharField(blank=True, max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('original_expires_at', models.DateTimeField()),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'pending'),
                        ('accepted', 'accepted'),
                        ('cancelled', 'cancelled'),
                        ('superseded', 'superseded'),
                    ],
                    default='pending',
                    max_length=16,
                )),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reinvite_count', models.PositiveSmallIntegerField(default=0)),
                ('last_reinvite_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sent_invitations',
                    to='core.coreuser',
                )),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='invitations',
                    to='core.organization',
                )),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'pending')),
                fields=('email',),
                name='unique_pending_invitation_per_email',
            ),
        ),
    ]
