# Generated by Django 5.0.13 on 2025-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalization',
            name='language_file',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='workflowlevel2sort',
            name='sort_array',
            field=models.JSONField(blank=True, help_text='Sorted JSON array of workflow levels', null=True),
        ),
    ]
